"""
Vidyut AI - In-App Border Screening Assistant Router
Endpoint: POST /vidyut-assist
Provides context-aware responses grounded in the current screen, specimen verification data,
tampering heatmaps, MRZ validation, and border control operating procedures.
"""

from typing import List, Optional, Dict, Any
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import os
import httpx

router = APIRouter(prefix="", tags=["assistant"])


class ChatMessage(BaseModel):
    role: str  # "user" | "assistant" | "system"
    content: str


class CaseDataContext(BaseModel):
    case_number: Optional[str] = None
    document_type: Optional[str] = None
    verdict: Optional[str] = None
    risk_score: Optional[float] = None
    tampering_score: Optional[float] = None
    face_match_confidence: Optional[float] = None
    face_match_verdict: Optional[str] = None
    validation_issues: Optional[List[str]] = []
    extracted_fields: Optional[Dict[str, Any]] = {}
    reason: Optional[str] = None
    checkpoint_location: Optional[str] = None


class AssistRequest(BaseModel):
    question: str
    screen: str  # "INTAKE" | "RESULTS" | "FACEMATCH" | "ALERTS" | "AUDIT" | "GENERAL"
    case_data: Optional[CaseDataContext] = None
    history: Optional[List[ChatMessage]] = []


class AssistResponse(BaseModel):
    answer: str
    suggested_followups: List[str]
    context_badge: Optional[str] = None


def generate_grounded_response(question: str, screen: str, case: Optional[CaseDataContext]) -> AssistResponse:
    """Generate high-precision domain-grounded response for border security screening."""
    q = question.lower().strip()
    followups = []
    context_badge = f"Screen: {screen}"

    # ─────────────────────────────────────────────────────────────
    # Case Results Context Inquiries
    # ─────────────────────────────────────────────────────────────
    if screen == "RESULTS" and case and (case.verdict or case.risk_score is not None):
        v = (case.verdict or "UNKNOWN").upper()
        score = case.risk_score if case.risk_score is not None else 0
        tamper = case.tampering_score if case.tampering_score is not None else 0
        issues = case.validation_issues or []
        doc_type = case.document_type or "Document"
        context_badge = f"{case.case_number or 'Case'} · {v} (Risk: {score})"

        if any(k in q for k in ["risk score", "score", "why is the risk", "calculate", "rating"]):
            ans = (
                f"**Risk Score Analysis ({score}/100 — Verdict: {v})**\n\n"
                f"The composite risk score is computed from three weighted screening dimensions:\n"
                f"1. **Tampering & Artifact Severity**: {tamper}% contribution (Error Level Analysis & high-frequency edge variance).\n"
                f"2. **Validation Rule Anomalies**: {len(issues)} detected issue(s) ({', '.join(issues) if issues else 'No structural errors'}).\n"
            )
            if case.face_match_confidence is not None:
                ans += f"3. **Biometric Face Disparity**: Match confidence is {case.face_match_confidence}%.\n\n"
            
            if score >= 70:
                ans += "**Operational Directive**: This specimen exceeds critical security thresholds. Flag for secondary physical inspection and supervisor review before granting border clearance."
            elif score >= 35:
                ans += "**Operational Directive**: Moderate risk detected. Cross-examine bearer against secondary government database records."
            else:
                ans += "**Operational Directive**: Low risk profile. Specimen passes automated integrity gates."
            
            followups = [
                "What does the tampering heatmap show?",
                "What are the next operational steps?",
                "How do I escalate this to a supervisor?"
            ]
            return AssistResponse(answer=ans, suggested_followups=followups, context_badge=context_badge)

        if any(k in q for k in ["mrz", "checksum", "parity", "ocr", "font", "alignment"]):
            ans = (
                f"**MRZ & Document Structure Verification for {doc_type}**\n\n"
                f"Standard ICAO 9303 / National ID standards mandate check-digit verification across Document Number, Date of Birth, and Expiration fields.\n\n"
            )
            if any("mrz" in i.lower() or "checksum" in i.lower() for i in issues):
                ans += (
                    f"⚠️ **Identified Failure**: The MRZ checksum parity failed mathematical validation (7-3-1 weight algorithm). "
                    f"This indicates the text characters on the specimen line were manually altered or generated by unauthorized software without recalculating standard check digits.\n\n"
                    f"**Action**: Request physical original document and inspect tactile microprinting under UV/white light."
                )
            else:
                ans += "✅ All MRZ checksums and optical character baseline alignments on this specimen verified successfully with zero parity mismatches."
            
            followups = [
                "Why did tampering heatmap flag this area?",
                "How to escalate this case?",
                "Show checklist for passport inspection"
            ]
            return AssistResponse(answer=ans, suggested_followups=followups, context_badge=context_badge)

        if any(k in q for k in ["tamper", "heatmap", "ela", "splice", "photo", "border"]):
            ans = (
                f"**Tampering & Spectral Heatmap Findings (Index: {tamper}%)**\n\n"
                f"The AI analysis runs multi-layer forensic detection:\n"
                f"• **Error Level Analysis (ELA)**: Detects compression rate variations between original document substrate and newly pasted photo/text.\n"
                f"• **Edge Gradient Consistency**: Identifies artificial boundary cuts around the portrait photo or personal data matrix.\n"
                f"• **Noise Residual Mapping**: Spots localized digital cloning, airbrushing, or digital font substitution.\n\n"
            )
            if case.reason:
                ans += f"**Specific Specimen Anomaly**: *{case.reason}*\n\n"
            ans += "**Recommendation**: Check whether the portrait photo exhibits halo artifacts, uneven pixel density, or mismatched paper grain under magnification."
            
            followups = [
                "What is the biometric match status?",
                "What are the next operational steps?",
                "Explain the Risk Score calculation"
            ]
            return AssistResponse(answer=ans, suggested_followups=followups, context_badge=context_badge)

        if any(k in q for k in ["next step", "protocol", "escalat", "action", "what should i do"]):
            ans = (
                f"**Standard Operating Protocol for {v} Specimen ({case.case_number or 'Current Case'})**\n\n"
                f"1. **Hold Specimen**: Maintain possession of the physical document.\n"
                f"2. **Secondary Biometric Verification**: Re-verify live facial capture if lighting or angle was suboptimal.\n"
                f"3. **Supervisor Escalation**: If verdict is `FAKE` or `SUSPICIOUS`, tap the **Alerts / Audit Console** to mark case status for supervisor concurrence.\n"
                f"4. **Log Chain of Custody**: Note checkpoint location ({case.checkpoint_location or 'Active Checkpoint'}) and timestamp in the incident log."
            )
            followups = [
                "How do I export case report?",
                "Explain MRZ checksum failure",
                "What is the biometric threshold?"
            ]
            return AssistResponse(answer=ans, suggested_followups=followups, context_badge=context_badge)

    # ─────────────────────────────────────────────────────────────
    # Intake Screen Inquiries
    # ─────────────────────────────────────────────────────────────
    if screen == "INTAKE" or any(k in q for k in ["format", "intake", "upload", "size", "reject", "lighting", "resolution"]):
        if any(k in q for k in ["format", "file", "extension", "type", "accepted"]):
            ans = (
                "**Accepted Specimen Formats & Specifications**\n\n"
                "• **Supported File Types**: High-resolution `JPG`, `PNG`, `WEBP`, or `PDF` scans.\n"
                "• **Maximum File Size**: 10 MB per file.\n"
                "• **Recommended Resolution**: 300+ DPI (minimum 1200×800 pixels) to allow sub-pixel forensic anti-aliasing inspection.\n"
                "• **Color Space**: Full 24-bit RGB (grayscale scans reduce tamper detection efficacy)."
            )
            followups = [
                "Why do document uploads get rejected?",
                "Best practices for document photo capture",
                "How does passport vs visa intake differ?"
            ]
            return AssistResponse(answer=ans, suggested_followups=followups, context_badge="Intake Guidelines")

        if any(k in q for k in ["reject", "fail", "why reject", "error"]):
            ans = (
                "**Common Reasons for Intake Rejection**\n\n"
                "1. **Severe Glare or Flash Reflection**: Obscures security microprinting or holographic overlay.\n"
                "2. **Excessive Corner Cropping**: When document outer edges or all 4 corners are clipped outside frame.\n"
                "3. **Low Resolution or Motion Blur**: Prevents OCR character recognition on MRZ lines.\n"
                "4. **Unsupported File Format**: Files exceeding 10MB or corrupt headers.\n\n"
                "💡 *Tip*: Place the document flat on a dark, non-reflective background with diffuse overhead lighting."
            )
            followups = [
                "What file formats are accepted?",
                "How to take live selfie with webcam?",
                "How does AI detect tampering?"
            ]
            return AssistResponse(answer=ans, suggested_followups=followups, context_badge="Intake Troubleshooting")

    # ─────────────────────────────────────────────────────────────
    # Face Match & Biometrics
    # ─────────────────────────────────────────────────────────────
    if screen == "FACEMATCH" or any(k in q for k in ["face", "biometric", "selfie", "webcam", "camera", "portrait"]):
        ans = (
            "**Biometric Face Matching Principles**\n\n"
            "• **128-Point Facial Landmark Mapping**: Measures inter-pupillary distance, jawline curvature, nasal bridge angle, and cheekbone topography.\n"
            "• **Threshold Criteria**:\n"
            "  - **>= 75% Match**: High confidence biometric match (`MATCH`).\n"
            "  - **50% - 74% Match**: Partial similarity; manual secondary review recommended (`INCONCLUSIVE`).\n"
            "  - **< 50% Match**: Disparity flag (`MISMATCH` / `FAKE` trigger).\n"
            "• **Troubleshooting Tips**: Remove hats, dark sunglasses, or heavy masks. Ensure facial plane is directly aligned with the checkpoint camera."
        )
        followups = [
            "What if traveler has aged significantly?",
            "How to retake webcam selfie?",
            "Explain risk score calculation"
        ]
        return AssistResponse(answer=ans, suggested_followups=followups, context_badge="Biometrics")

    # ─────────────────────────────────────────────────────────────
    # Supervisor / Audit / Escalation Inquiries
    # ─────────────────────────────────────────────────────────────
    if screen == "AUDIT" or any(k in q for k in ["audit", "supervisor", "escalate", "export", "report", "csv"]):
        ans = (
            "**Supervisor Review & Audit Trail Operations**\n\n"
            "• **Audit Console Access**: Supervisors have centralized oversight across all border checkpoints (Attari-Wagah, Petrapole, Moreh, etc.).\n"
            "• **Case Review**: Filter by verdict (`FAKE`, `SUSPICIOUS`, `GENUINE`) or date range to inspect officer decisions.\n"
            "• **Chain-of-Custody Export**: Download structured JSON/CSV audit reports for inter-agency criminal investigations.\n"
            "• **Override Authority**: Supervisors can attach formal rationale notes and reclassify algorithmic verdicts."
        )
        followups = [
            "How to filter cases by checkpoint?",
            "What are the system risk thresholds?",
            "How to export audit reports?"
        ]
        return AssistResponse(answer=ans, suggested_followups=followups, context_badge="Supervisor Console")

    # ─────────────────────────────────────────────────────────────
    # General Fallback
    # ─────────────────────────────────────────────────────────────
    ans = (
        f"**Vidyut AI Border Assistant Guidance**\n\n"
        f"Regarding your query: *\"{question}\"*\n\n"
        f"• **Screening Module**: Currently assisting on the **{screen}** console.\n"
        f"• **Capabilities**: I can analyze active specimen risk scores, explain MRZ checksum errors, detail Error Level Analysis heatmaps, advise on biometric face match thresholds, and guide MHA escalation workflows.\n\n"
        f"Feel free to ask a specific question or tap any of the quick-action prompts below."
    )
    followups = [
        "Explain Risk Score & Verdicts",
        "What file formats are accepted at intake?",
        "What does MRZ checksum error mean?",
        "How do I escalate to a supervisor?"
    ]
    return AssistResponse(answer=ans, suggested_followups=followups, context_badge="Vidyut AI")


async def try_llm_assist(question: str, screen: str, case: Optional[CaseDataContext], history: List[ChatMessage]) -> Optional[str]:
    """Attempt LLM generation if GEMINI_API_KEY or OPENAI_API_KEY is available in environment."""
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        return None

    system_prompt = (
        "You are Vidyut AI, an authoritative, helpful, and technically precise in-app AI assistant for Indian Ministry of Home Affairs (MHA) "
        "border control screening officers using the AI-Based Fake Identity & Document Screening System. "
        "Provide direct, concise, and actionable guidance grounded in the provided document context, forensic algorithms (MRZ ICAO 9303, ELA tampering, "
        "deep neural face biometrics), and border security standard operating procedures. Keep responses structured with markdown bullet points."
    )

    context_str = f"Current Screen: {screen}\n"
    if case:
        context_str += (
            f"Case Number: {case.case_number or 'N/A'}\n"
            f"Document Type: {case.document_type or 'N/A'}\n"
            f"Verdict: {case.verdict or 'N/A'}\n"
            f"Risk Score: {case.risk_score or 0}/100\n"
            f"Tampering Score: {case.tampering_score or 0}%\n"
            f"Validation Issues: {', '.join(case.validation_issues or [])}\n"
            f"Reason: {case.reason or 'None'}\n"
            f"Checkpoint: {case.checkpoint_location or 'General'}\n"
        )

    try:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
        payload = {
            "contents": [
                {"role": "user", "parts": [{"text": f"System Context:\n{system_prompt}\n\nActive Specimen Context:\n{context_str}\n\nOfficer Question: {question}"}]}
            ]
        }
        async with httpx.AsyncClient(timeout=8.0) as client:
            resp = await client.post(url, json=payload)
            if resp.status_code == 200:
                data = resp.json()
                text = data["candidates"][0]["content"]["parts"][0]["text"]
                return text
    except Exception:
        pass
    return None


@router.post("/vidyut-assist", response_model=AssistResponse)
async def vidyut_assist(payload: AssistRequest):
    """Context-aware assistant endpoint for Vidyut AI."""
    # Attempt LLM call if configured
    llm_answer = await try_llm_assist(
        question=payload.question,
        screen=payload.screen,
        case=payload.case_data,
        history=payload.history or []
    )

    if llm_answer:
        # Construct follow-ups
        followups = [
            "Explain tampering heatmap details",
            "What are recommended next steps?",
            "How to escalate to supervisor?"
        ]
        badge = f"{payload.case_data.case_number} · {payload.case_data.verdict}" if payload.case_data and payload.case_data.case_number else f"Screen: {payload.screen}"
        return AssistResponse(
            answer=llm_answer,
            suggested_followups=followups,
            context_badge=badge
        )

    # Use grounded rule-based expert engine
    return generate_grounded_response(
        question=payload.question,
        screen=payload.screen,
        case=payload.case_data
    )
